GET http://localhost:3000/api/auth/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiam9uQGdtYWlsLmNvbSIsImlhdCI6MTcyNzYzNTYwMCwiZXhwIjoxNzI3NjM5MjAwfQ.lCQ93Sh28dSFTikX-z7JhtF6b5Jc80wTvgmx0PwvXM8
###

POST http://localhost:3000/api/auth/register HTTP/1.1
content-type: application/json

{
    "email": "aaaaa",
    "password": "123"
}

###
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "jo3n@gmail.com",
    "password": "Jon*123334"
}



###
GET http://localhost:3000/api/auth/test


### 
GET http://localhost:3000/api/getList?pageNo=1&limit=3&sortBy=desc&search=a


### 
GET http://localhost:3000/api/getListSequalize?page=1&limit=5&sortOrder=DESC